print("Welcome to the Startup Name Generator!")
word = input("What is the word you love?\n")
industry = input("What industry is your startup in?\n")
print("Here are your startup names: ")
print("1. ", word + industry)
print("2. ", word[:2] + industry[-2:])
print("3. ", word + industry[-2:])
print("4. ", word[:2] + industry)
print("5. ", word[:2] + industry[:2])
print("6. ", industry + word)
print("7. ", industry[:2] + word[-2:])
print("8. ", industry + word[-2:])
print("9. ", industry[:2] + word)
print("10. ", industry[:2] + word[:2])