question_data = [
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "General Knowledge",
            "question": "The Sun rises from the North.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "General Knowledge",
            "question": "The mitochondria is the powerhouse of the cell.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "General Knowledge",
            "question": "Water is naturally coloured blue.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "General Knowledge",
            "question": "March 10th is also known as Mar10 Day.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "General Knowledge",
            "question": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "General Knowledge",
            "question": "The color orange is named after the fruit.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "General Knowledge",
            "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "General Knowledge",
            "question": "All strawberries are red.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "General Knowledge",
            "question": "When you cry in space, your tears stick to your face.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "General Knowledge",
            "question": "Gumbo is a stew that originated in Louisiana.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
    ]


